project:
  type: website
  output-dir: docs

website:
  title: "Katie's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
      - walkthrough.qmd
      - academicpaper.qmd 
      - profilepiece.qmd 
  page-footer: 
    left: "Copyright 2022, Katie Coolidge" 
    right: 
      - icon: github
        href: https://github.com/kcoolidge

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



