---
title: "Portfolio"
about:
  template: jolla
  links:
    - icon: Jack Carlson Revival of a Lost Culture
      text: Jack Carlson Revival of a Lost Culture
      href: https://issuu.com/george.gwfba/docs/george_iii
    - icon: Astrid Voss A Rising Star
      text: Astrid Voss A Rising Star
      href: https://issuu.com/george.gwfba/docs/george_iii
    - text: New Balance Unapologetically Authentic
      href: https://issuu.com/george.gwfba/docs/george_issue_iv_pages_-3
  
---

 My Articles
 
 Jack Carlson
 
My first piece is an article feature on Jack Carlson, the founder of clothing company Rowing Blazers. I conducted the interview during the height of covid when the magazine's theme was to feature stories about globalization. I decided to conduct my piece on the opposite-- featuring a clothing brand striving to preserve a dynamic preppy audience.

Astrid Voss

My second piece features a high school fashion model from Massachusetts who walked for Burberry during their virtually broadcasted show during covid. The article attempts to capture the experience of working for world renowned fashion houses when the typical environment changed drastically.

New Balance

My third piece is based off of a paper I wrote for a college marketing class. The goal was to find a company caught in an interesting part of the product life cycle. New Balance was featured because in 2021 they were experiencing a large overhaul in brand image and marketing.


Please find the hyperlinks to each article below:

