---
title: "Profile Piece"
about:
  template: jolla
editor: 
  markdown: 
    wrap: sentence
---
In my intro to news writing class I wrote a piece on my close friend's mother who had an amazing career that I admired.

She was a talent agent for a bunch of very famous companies that at various points were bicoastal and allowed her to attend very glamorous events.

---

Profile: Geri Campbell

Celebrities will always procure a certain fascination from the populace. But, according to Geri Campbell, many times their world was enclosed by a thin, shimmering veneer; and it was her job to create it as a talent agent. 

“Truth be told I wanted to be an actor,” Campbell said while nestled into her couch with pet schnauzer in tow. 

Instead, she got as close as humanly possible to celebrities. 

Entertainment Editor, Special Projects Director and Celebrity Talent Producer were titles held by Campbell. Reese Witherspoon, Kate Moss and Julia Roberts were household names in her family. Campbell’s job was to procure talent. She would work in tandem with renowned publications and photographers to create, book and capture celebrities. Magazine covers, reality TV and movie reviews were not weekend hobbies, but components of her professional life. 

Inspiration for her career first stemmed from magazines and television. Campbell was charmed by anything with a fashionable female lead: “Bewitched” and “That Girl.” 

This interest was later fostered by her step-dad, Sam Novenstern, who was head of broadcasting for Madison Square Garden. The New York Knicks and Rangers would frequent her house for dinner. 

“I was a fun friend to have in high school because I would take friends to concerts or games at Madison Square Garden,” she said. 

After high school, Campbell went on to study communications at Boston University. While in undergrad she became the creative director of AdLab, a student run ad agency. Campbell’s pinnacle moment was creating the infamous “neighborhood watch eye” that is still in use today.

While Boston was great for school, the second Campbell graduated she rushed back to New York, her favorite city. Her first job was for Diener Hauser Bates Advertising, whom she had previously worked for over the summers. There, she wrote taglines and trailers for major motion pictures at just 23. 

Even though she enjoyed her experience at Bates, Campbell was constantly changing jobs. The industry, while idealized, is extremely volatile. However, no industry more so than fashion: exactly where Campbell ended up. Mirabella Magazine, run by Grace Mirabella, became Campbell’s “war of the worlds.” Blood and stiff competition ran deep between Vogue and Mirabella making Campbell’s job a nightmare. As a model editor, she needed to book the models. That’s not an easy thing to do when you have Vogue undermining your efforts. Campbell adapted to the challenge. She iconically spearheaded the movement of putting actresses on magazine covers.

“We couldn’t get the models we were used to working with...so I put Julia Roberts on the cover because no one wanted them at the time.”

Besides practically inventing the celebrity cover movement, Campbell was a founding editor at Allure magazine, opened her own production company and was the director of talent for VH1. Even though she’s played many roles in life, the one that makes her most proud is being a mother.

Campbell’s legendary career will likely live on through her 21-year-old daughter, Nathalie, who also wants to be a talent agent. Campbell raised Nathalie between two coasts, L.A. and Bedford, NY, while juggling her job for VH1. Campbell fought both Condé Nast and Viacom relentlessly to work two days from home in order to raise her daughter. It was previously unheard of. 

“I helped to change policy by doing that,” she said. 

It was one of her proudest moments. 

The two of them are about as similar as can be. But, Campbell voiced her doubts. The job is constantly about making the impossible possible. She admitted the job made her meaner.
 
“You had to be [mean]. People were irrational and difficult about things completely out of your control,” she said.

 In her old office, Campbell hung a sign saying “no, Grace Kelly is not available” because there was truly no ask that was too crazy.

Despite the challenges, her career also taught her not to take things so seriously. Yes, the drama was ridiculous, but the world Campbell entertained was completely illusory. She saw supermodels with no makeup, actresses not in character. Sometimes that was extraordinary, but other times would fall short of expectations. 

“I did a lot for people in the industry...there are a lot of people and models that I gave their first job to. I’m not legendary in any way, but in those ways I made a mark,” she said.

She was the magician behind the glittering facade we see on magazine covers and television. Her job was to always make fantasy a reality. And she did a pretty good job.


.
